core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("portal.urls")),
    path("", include("apiHuge.urls")), 
    path("shareshack/", include("shareshack.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    #There is nothing at the simple /accounts/ url. Use accounts/login for testing.
]

shareshack/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('items/', views.ItemListView.as_view(), name='items'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('department/<int:pk>', views.DepartmentDetailView.as_view(), name='department-items'),
    path('myitems/', views.LoanedItemsByUserListView.as_view(), name='my-borrowed-items'),
    path('checkedoutitems/', views.CheckedOutItemsListView.as_view(), name='all-checked-out-items'),
    path('item/create/', views.ItemCreate.as_view(), name='item-create'),
    path('item/<int:pk>/renew/', views.renew_item_librarian, name='renew-item-librarian'),
    path('item/<int:pk>/transaction/', views.TransactionEntry.as_view(), name='librarian-transaction'),
]

shareshack/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User
from datetime import date
from django.utils.safestring import mark_safe

class Department(models.Model):
    """Model representing store department or section."""
    name = models.CharField(max_length=200)

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
    def get_absolute_url(self):
        """Returns the url to access list of items in department."""
        return reverse('department-items', args=[str(self.id)])

class Item(models.Model):
    department = models.ForeignKey('Department', models.SET_NULL, blank=True, null=True)
    writtenId = models.CharField('Written ID', help_text= mark_safe('<i>The number written on item</i>'), max_length=30, unique=True)
    name = models.CharField(max_length=30, help_text= mark_safe('<i>e.g. cordless drill 3</i>'))
    date_added = models.DateField(auto_now_add=True)
    condition = models.TextField(max_length=100, help_text='Update changes upon return if necessary', blank=True, null=True)
    donor =  models.ForeignKey(User, related_name='donor', on_delete=models.SET_NULL, null=True, blank=True)
    borrower = models.ForeignKey(User, related_name='borrower', on_delete=models.SET_NULL, null=True, blank=True)
    due_back = models.DateField(blank=True, null=True)
    image = models.CharField(max_length = 200, blank=True)

    LOAN_STATUS = (
        ('a', 'Available'),
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Item availability',
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['status','due_back']
        permissions = (
            ("can_mark_returned", "Can checkout and return items"), 
            ("donation_intake", "Process new donations"),
            )

    def __str__(self):
        return f'{self.writtenId} ({self.name})'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this item."""
        return reverse('item-detail', args=[str(self.id)])

class Transaction(models.Model):
    librarian = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='librarian')
    writtenId = models.CharField("Written ID", max_length=30, default='0000')
    name = models.CharField(max_length=30)
    condition = models.TextField(max_length=100, blank=True, null=True)
    checked_out_to = models.ForeignKey(User, models.SET_NULL, related_name='checked_out_to', blank=True, null=True)
    due_back = models.DateField(blank=True, null=True)
    transaction_date= models.DateField(auto_now_add=True)

shareshack/forms.py
import datetime


from django import forms
from django.forms import ModelForm

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from shareshack.models import Item

class DateInput(forms.DateInput):
    input_type = 'date'

class RenewItemForm(forms.Form):
    renewal_date = forms.DateField(widget=forms.DateInput(), help_text="Enter a date between now and 4 weeks (YYYY-MM-DD).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
class TransactionForm(ModelForm):
    class Meta:
        model = Item
        fields = ['writtenId','name', 'borrower','due_back', 'condition']
        help_texts = {
            'due_back': 'Press X for returns',
            'condition': 'e.g. 10/12/18 small crack on rim',
            'borrower': 'select "-----" for returns',
        }
        widgets = {
            'due_back': DateInput(),
            'writtenId' : forms.HiddenInput(),
            'name' : forms.HiddenInput(),
        }
        

shareshack/views.py
from django.shortcuts import render
from shareshack.models import Department, Item, Transaction
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

def home(request):
    string1 = 'Hi There'
    string2 = 'Goodbye'
    department_list = Department.objects.all()
    context = {
        'department_list': department_list,
        'string1': string1,
        'string2': string2
    }
    return render(request, 'home.html', context = context)

class ItemListView(generic.ListView):
    model = Item

class ItemDetailView(generic.DetailView):
    model = Item

class DepartmentDetailView(generic.DetailView):
    model = Department
    template_name ='department_items.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(DepartmentDetailView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['department_list'] = Department.objects.all()
        return context

class LoanedItemsByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing items on loan to current user."""
    model = Item
    template_name ='item_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Item.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class CheckedOutItemsListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based staff only view listing all items checked out from facility."""
    permission_required = 'shareshack.can_mark_returned'
    model = Item
    template_name ='all_checked_out_items.html'
    paginate_by = 10

    def get_queryset(self):
        return Item.objects.filter(status__exact='o').order_by('due_back')

class ItemCreate(CreateView):
    model = Item
    fields = ['department', 'writtenId', 'name', 'donor',
        'condition']  

import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from shareshack.forms import RenewItemForm, TransactionForm

#Checkout/Return View
class TransactionEntry(PermissionRequiredMixin, UpdateView):
    permission_required = 'shareshack.can_mark_returned'
    template_name = "item_transaction_entry.html"

    def get(self,request,pk):
        item_obj = get_object_or_404(Item, pk=pk)
        form = TransactionForm(instance=item_obj)
        return render(request, self.template_name, {'form':form, 'item':item_obj })

    def post(self,request,pk):
        item_obj = get_object_or_404(Item, pk=pk)
        form = TransactionForm(request.POST, instance=item_obj)
        errors = None
        if form.is_valid():

            Transaction.objects.create(
                librarian = request.user,
                writtenId = form.cleaned_data.get('writtenId'),
                name = form.cleaned_data.get('name'),
                condition = form.cleaned_data.get('condition'),
                due_back = form.cleaned_data.get('due_back'),
                checked_out_to = form.cleaned_data.get('borrower'),
            )

            form.save()

            # return HttpResponseRedirect("/shareShack/items")
            return HttpResponseRedirect(reverse('index'))
        if form.errors:
            #print(form.errors)
            errors = form.errors

        context = {'form':form, 'errors':errors}
        return render(request, self.template_name, context)


#Renew View
@login_required
@permission_required('shareshack.can_mark_returned', raise_exception=True)
def renew_item_librarian(request, pk):
    """View function for renewing a specific item by librarian."""
    item_instance = get_object_or_404(Item, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewItemForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            item_instance.due_back = form.cleaned_data['renewal_date']
            item_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-checked-out-items') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewItemForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'item_instance': item_instance,
    }

    return render(request, 'item_renew_librarian.html', context)

shareshack/templates/all_checked_out_items.html
{% extends "base_generic.html" %}

{% block content %}
  {% if item_list %}
  <h1>Masterlist of checked out items:</h1>
  <ul>
    {% for item in item_list %}
    <li class="{% if item.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'item-detail' item.pk %}">{{item.writtenId}}</a> | {{item.name}} | Due back: {{ item.due_back }}
    | {% if perms.shareshack.can_mark_returned %}- <a href="{% url 'renew-item-librarian' item.id %}">Renew</a>  {% endif %}
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no checked out items.</p>
  {% endif %}
{% endblock %}

shareshack/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}  
<head>
  {% block title %}<title>Share Shack</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Add additional CSS in static file --> 
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a id="home" href="{% url 'home' %}">Home</a></li>
          <br>
          {% block departments %}
            {% if department_list %}
            {% for department in department_list %}
            <li>
             <a class="f" href="{{ department.get_absolute_url }}">{{ department.name }}</a>
            </li>
            {% endfor %}
            {% else %} 
            <li>^Go Back</li>
            {% endif %}
          {% endblock %}
        <br>
          {% if user.is_authenticated %}
          <li class="f">Hello: <i>{{ user.get_username }}</i></li>
          <li><a href="{% url 'my-borrowed-items' %}">Your checked-out items</a></li>
          <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          {% else %}
           <li><a href="{% url 'login'%}?next={{request.path}}">User/Staff Login</a></li>
          {% endif %}
        <br> 
          {% if perms.shareshack.can_mark_returned %}
          <!-- All staff has this permission -->
          <li>Staff</li>
          <li><a href="{% url 'all-checked-out-items' %}">All items out</a></li>
            {% if perms.shareshack.donation_intake %}
            <li><a href="{% url 'item-create' %}">New Item Donation</a></li>
            {% endif %}
          {% else %}
          {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

shareshack/templates/department_items.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
  <h1> {{ department.name }}</h1>
  <ul>
  {% if department.item_set.all %} 
    {% for item in department.item_set.all %}
    <li><img src="{{item.image}}" alt="{{item.image}}">{{ item.name }} | <a href="{{ item.get_absolute_url }}">{{ item.writtenId }}</a> | {{item.get_status_display}}</li> 
    <br>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no items here.</p>
  {% endif %}
{% endblock %}

shareshack/templates/home.html
{% extends "base_generic.html" %}
{% load static %} 

{% block content %}

  <h1 style="color:rgb(5, 53, 23);text-align:center;">SHARE SHACK</h1>
  <p>Welcome to Share Shack; a "Library of Things" inventory management system.</p>
  <span><i>Don't have room for tools you rarely use?</i> Borrow/Donate with us!</span>
  
  
  <div class="card-deck">
    <div class="card">
      <img class="card-img-top" src="https://www.gardeningknowhow.com/wp-content/uploads/2017/05/wheelbarrow-400x267.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Wheel barrows</h5>
        <p class="card-text">Great for invasive species removal volunteer parties.</p>
        <a href="department/2" class="btn btn-primary">Browse Landscaping</a>
      </div>
    </div>
    <div class="card">
      <img class="card-img-top" src="https://www.thespruce.com/thmb/hmff0JAyY3DXghdejLlvGjK6xvg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/SPR_OVERALLBEAUTY_4.jpg-4f883e8f21d84113a917f475e6386077.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Ladders</h5>
        <p class="card-text">Use at your own risk!</p>
        <a href="department/1" class="btn btn-primary">Browse General Tools</a>
      </div>
    </div>
    <div class="card">
      <img class="card-img-top" src="https://i.ebayimg.com/images/g/mo8AAOSwyQlg9tba/s-l640.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Stock Pots</h5>
        <p class="card-text">Feed the whole collective.</p>
        <a href="department/5" class="btn btn-primary">Browse Catering </a>
      </div>
    </div>
  </div>

  <!-- 
  <h2>Dynamic content</h2>
  <p>Test context from views.py passing into template </p>
  <ul>
    <li><strong>String 1:</strong> {{ string1 }}</li>
    <li><strong>String 2:</strong> {{ string2 }}</li>
  </ul>
  -->

{% endblock %}

shareshack/templates/item_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
  {% if item_list %}
  <h1>Your checked out items:</h1>
  <ul>
    {% for item in item_list %}
    <li class="{% if item.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'item-detail' item.pk %}">{{item.writtenId}}</a>
       | {{item.name}} | Due back: {{ item.due_back }} | {% if perms.shareshack.can_mark_returned %}- <a href="{% url 'renew-item-librarian' item.pk %}">Renew</a>  {% endif %}
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>You have no checked out items.</p>
  {% endif %}
{% endblock %}

shareshack/templates/item_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ item_instance.name }}</h1>
  <p>Borrower: {{ item_instance.borrower }}</p>
  {% if item_instance.is_overdue %}
  <p{% if item_instance.is_overdue %} class="text-danger"{% endif %}>Overdue since: {{ item_instance.due_back }}</p>
  {% else %}
  <p>Current due date: {{ item_instance.due_back }}</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

shareshack/templates/item_transaction_entry.html
{% extends "base_generic.html" %}
{% block title %} Check Out{% endblock %}

{%block content%}
<center><h3>{{item.writtenId}} | {{item.name }}</h3></center>
<div class="about">
  {% if errors %}
  {{ errors }}
  {% endif %}
  <form method = 'post'>
    {% csrf_token %}
    <table>
    {{ form.as_table}}
    </table>
    <button type="submit">Submit</button>
  </form>
</div>
{%endblock%}